name: License Check

on: [push]

jobs:
  check-license-headers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check license headers
      run: |
        ./scripts/check_license_headers.sh
