apiVersion: apps/v1
kind: Deployment
metadata:
  name: constraint-lattice
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: constraint-lattice
  template:
    metadata:
      labels:
        app: constraint-lattice
    spec:
      containers:
      - name: constraint-lattice
        image: us-central1-docker.pkg.dev/teak-amphora-464204-a7/constraint-lattice-repo/constraint-lattice:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: constraint-lattice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: constraint-lattice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
