name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

env:
  HF_HUB_OFFLINE: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          pip install -e .[dev]
          pip install pytest-cov
          pip install ruff mypy

      - name: Lint with Ruff
        run: ruff check .

      - name: Type-check with MyPy
        run: mypy .

      - name: Format-check with Black
        run: black --check .

      - name: Run tests with coverage
        run: pytest --cov=. -q

      - name: Upload coverage report
        uses: codecov/codecov-action@v4


      - name: vLLM stub smoke test
        run: pytest --cov=. -q tests/smoke/test_vllm_stub.py

  pytest:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          pip install -e .[dev]
          pip install pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=. -q

      - name: Upload coverage report
        uses: codecov/codecov-action@v4


      - name: vLLM stub smoke test
        run: pytest --cov=. -q tests/smoke/test_vllm_stub.py

