name: CLA Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DCO/CLA verification
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'CLA-signatures.json'
