name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGION: us-central1
  SERVICE_NAME: constraint-lattice
  REPOSITORY: constraint-lattice  # Artifact Registry repo name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          # These secrets must be configured in the repository → Settings → Secrets & variables → Actions
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gcloud"

      - name: Build and push container image
        run: |
          IMAGE_URI="us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          gcloud builds submit --tag "$IMAGE_URI" --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_URI \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars CLATTICE_LOG_LEVEL=INFO \
            --min-instances=0 \
            --max-instances=10
