name: Integration Test Stack

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  integration:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.9-dind
        privileged: true
        options: >-
          --dns 8.8.8.8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (for Compose)
        uses: docker/setup-buildx-action@v3

      - name: Compose up (build & detach)
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for container health
        run: |
          ./scripts/wait-for-health.sh constraint-lattice-api-local constraint-lattice-redis-local wordpress-db-local wordpress-local

      - name: Smoke tests – FastAPI
        run: |
          curl -f http://localhost:8000/health

      - name: Smoke tests – WordPress login page
        run: |
          curl -f http://localhost:8080/wp-login.php

      - name: Show container logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.yml logs --no-color

      - name: Compose down
        if: always()
        run: |
          docker compose -f docker-compose.yml down -v
